### ISSUE TITLE
No sensor

### ISSUE THREAD

**Issue by TargetCrafter** [eifinger/hass-foldingathomecontrol#1]
## Version of the custom_component
v0.0.1

## Configuration

```yaml

foldingathomecontrol:
  - address: "192.168.2.2"
    port: 36330
    password: !secret fah_password

```

## Describe the bug
After installation and configuration i don't see the sensor, not even after a restart.

## Debug log

N/A
